version: "3"

services:

  registry:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.cbec.registry:1.0.0-SNAPSHOT
    environment:
      - PARAMS
    networks:
      - toolbox
    ports:
      - 29000:29000

  gateway:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.cbec.gateway:1.0.0-SNAPSHOT
    environment:
      - PARAMS
    ports:
      - 28888:28888
    networks:
      - toolbox

  mysql:
    restart: always
    image: mariadb:10
    networks:
      - toolbox
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  dbbackup:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.cbec.dbbackup:1.0.0-SNAPSHOT
    networks:
      - toolbox
    environment:
      - MYSQL_ROOT_PASSWORD
    depends_on:
      - mysql
    volumes:
      - ./data/dbbackup:/backup

  auth:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.cbec.auth:1.0.0-SNAPSHOT
    networks:
      - toolbox
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - PARAMS

  spider:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.cbec.spider:1.0.0-SNAPSHOT
    networks:
      - toolbox

  messager:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.cbec.messager:1.0.0-SNAPSHOT
    networks:
      - toolbox

  goods:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.cbec.goods:1.0.0-SNAPSHOT
    networks:
      - toolbox
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - PARAMS

  logistics:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.cbec.logistics:1.0.0-SNAPSHOT
    networks:
      - toolbox
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - PARAMS

  order:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.cbec.order:1.0.0-SNAPSHOT
    networks:
      - toolbox
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - PARAMS

  web:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.cbec.web:1.0.0-SNAPSHOT
    networks:
      - toolbox
    ports:
      - 20080:80

networks:
  toolbox:
    driver: bridge
