FROM adoptopenjdk/openjdk11-openj9:alpine-jre

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk add tzdata && \
    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
