SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `t_country`;
CREATE TABLE `t_country`  (
  `id` varchar(16) NOT NULL COMMENT '国家ID',
  `bcode` varchar(16) NOT NULL COMMENT '国家二字码',
  `name` varchar(256) NOT NULL COMMENT '名字',
  `english_name` varchar(256) NOT NULL DEFAULT '' COMMENT '英文名',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_bcode`(`bcode`),
  KEY `idx_name`(`name`)
) ENGINE = InnoDB COMMENT = '国家信息表';

INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('1', 'AW', '阿鲁巴', 'ARUBA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2', 'GL', '格陵兰岛', 'GREENLAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('3', 'GE', '格鲁吉亚', 'GEORGIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('4', 'CO', '哥伦比亚', 'COLOMBIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('5', 'GP', '瓜德罗普', 'GUADELOUPE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('6', 'GU', '关岛', 'GUAM');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('10', 'CU', '古巴', 'CUBA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('11', 'OM', '阿曼', 'OMAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('13', 'GY', '圭亚那', 'GUYANA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('18', 'HT', '海地', 'HAITI');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('22', 'AD', '安道尔', 'ANDORRA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('24', 'KR', '韩国', 'REPUBLIC OF KOREA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('30', 'NL', '荷兰', 'NETHERLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('35', 'HN', '洪都拉斯', 'HONDURAS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('40', 'AO', '安哥拉', 'ANGOLA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('44', 'GH', '加纳', 'GHANA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('45', 'CA', '加拿大', 'CANADA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('49', 'KH', '柬埔寨', 'CAMBODIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('50', 'GA', '加蓬', 'GABON');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('52', 'DJ', '吉布提', 'DJIBOUTI');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('53', 'CZ', '捷克', 'CZECH REPUBLIC');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('56', 'ZW', '津巴布韦', 'ZIMBABWE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('58', 'GN', '几内亚', 'GUINEA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('66', 'KY', '开曼群岛', 'CAYMAN ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('67', 'CM', '喀麦隆', 'CAMEROON');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('69', 'QA', '卡塔尔', 'QATAR');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('70', 'HR', '克罗地亚', 'CROATIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('71', 'KM', '科摩罗', 'COMOROS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('73', 'KE', '肯尼亚', 'KENYA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('74', 'CI', '科特迪瓦', 'COTE DIVOIRE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('75', 'KW', '科威特', 'KUWAIT');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('76', 'CK', '库克群岛', 'COOK ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('81', 'LA', '老挝', 'LAOS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('82', 'LV', '拉脱维亚', 'LATVIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('83', 'AG', '安提瓜', 'ANTIGUA AND BARBUDA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('87', 'LB', '黎巴嫩', 'LEBANON');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('88', 'LR', '利比里亚', 'LIBERIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('89', 'LY', '利比亚', 'LIBYA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('92', 'AU', '澳大利亚', 'AUSTRALIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('94', 'LT', '立陶宛', 'LITHUANIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('95', 'RE', '留尼汪岛', 'REUNION ISLAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('97', 'RO', '罗马尼亚', 'ROMANIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('99', 'LU', '卢森堡', 'LUXEMBOURG');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('100', 'RW', '卢旺达', 'RWANDA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('102', 'AT', '奥地利', 'AUSTRIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('104', 'MV', '马尔代夫', 'MALDIVES');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('105', 'MT', '马耳他', 'MALTA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('106', 'MY', '马来西亚', 'MALAYSIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('107', 'MW', '马拉维', 'MALAWI');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('108', 'ML', '马里', 'MALI');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('110', 'MU', '毛里求斯', 'MAURITIUS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('111', 'MK', '马其顿', 'MACEDONIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('112', 'MO', '中国澳门', 'MACAO CHINA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('113', 'MQ', '马提尼克', 'MARTINIQUE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('115', 'US', '美国', 'UNITED STATES');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('117', 'MN', '蒙古', 'MONGOLIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('118', 'BD', '孟加拉国', 'BANGLADESH');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('121', 'MM', '缅甸', 'MYANMAR');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('123', 'PE', '秘鲁', 'PERU');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('124', 'DM', '多米尼克', 'DOMINICA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('125', 'MD', '摩尔多瓦', 'MOLDOVA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('126', 'MA', '摩洛哥', 'MOROCCO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('127', 'MC', '摩纳哥', 'MONACO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('128', 'MZ', '莫桑比克', 'MOZAMBIQUE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('130', 'AZ', '阿塞拜疆', 'AZERBAIJAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('131', 'MX', '墨西哥', 'MEXICO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('133', 'NA', '纳米比亚', 'NAMIBIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('135', 'ZA', '南非', 'SOUTH AFRICA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('140', 'BB', '巴巴多斯', 'BARBADOS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('143', 'NP', '尼泊尔', 'NEPAL');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('144', 'NI', '尼加拉瓜', 'NICARAGUA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('147', 'NE', '尼日尔', 'NIGER');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('148', 'NG', '尼日利亚', 'NIGERIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('150', 'NO', '挪威', 'NORWAY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('152', 'PW', '帕劳', 'PALAU');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('154', 'PT', '葡萄牙', 'PORTUGAL');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('160', 'BS', '巴哈马', 'BAHAMAS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('163', 'JP', '日本', 'JAPAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('165', 'SE', '瑞典', 'SWEDEN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('166', 'CH', '瑞士', 'SWITZERLAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('167', 'SV', '萨尔瓦多', 'EL SALVADOR');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('168', 'RS', '塞尔维亚', 'SERBIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('169', 'SL', '塞拉利昂', 'SIERRA LEONE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('170', 'SN', '塞内加尔', 'SENEGAL');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('171', 'BY', '白俄罗斯', 'BELARUS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('172', 'CY', '塞浦路斯', 'CYPRUS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('173', 'SC', '塞舌尔', 'SEYCHELLES');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('174', 'WS', '萨摩亚', 'SAMOA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('182', 'BM', '百慕大', 'BERMUDA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('184', 'NULL', '圣基茨', 'SAINT KITTS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('185', 'SM', '圣马力诺', 'SAN MARINO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('190', 'LK', '斯里兰卡', 'SRI LANKA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('191', 'PK', '巴基斯坦', 'PAKISTAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('192', 'SK', '斯洛伐克', 'SLOVAKIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('193', 'SZ', '斯威士兰', 'SWAZILAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('194', 'SD', '苏丹', 'SUDAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('197', 'SR', '苏里南', 'SURINAME');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('201', 'AF', '阿富汗', 'AFGHANISTAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('202', 'PY', '巴拉圭', 'PARAGUAY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('203', 'TH', '泰国', 'THAILAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('205', 'TW', '中国台湾', 'TAIWAN CHINA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('209', 'TO', '汤加', 'TONGA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('211', 'TZ', '坦桑尼亚', 'TANZANIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('212', 'NULL', '塔希堤', 'TAHITI');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('213', 'PS', '巴勒斯坦', 'PALESTINE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('216', 'TR', '土耳其', 'TURKEY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('217', 'TN', '突尼斯', 'TUNISIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('218', 'VU', '瓦努阿图', 'VANUATU');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('219', 'GT', '危地马拉', 'GUATEMALA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('223', 'VE', '委内瑞拉', 'VENEZUELA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('224', 'BN', '文莱', 'BRUNEI DARUSSALAM');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('226', 'UG', '乌干达', 'UGANDA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('231', 'UA', '乌克兰', 'UKRAINE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('232', 'BH', '巴林', 'BAHRAIN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('233', 'UY', '乌拉圭', 'URUGUAY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('240', 'HK', '中国香港', 'HONG KONG CHINA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('241', 'PA', '巴拿马', 'PANAMA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('242', 'ES', '西班牙', 'SPAIN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('243', 'GR', '希腊', 'GREECE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('248', 'SG', '新加坡', 'SINGAPORE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('250', 'NZ', '新西兰', 'NEW ZEALAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('254', 'HU', '匈牙利', 'HUNGARY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('259', 'SY', '叙利亚', 'SYRIAN ARAB REPUBLIC');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('261', 'JM', '牙买加', 'JAMAICA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('262', 'BG', '保加利亚', 'BULGARIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('263', 'AM', '亚美尼亚', 'ARMENIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('269', 'YE', '也门', 'YEMEN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('272', 'IT', '意大利', 'ITALY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('274', 'IQ', '伊拉克', 'IRAQ');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('275', 'IR', '伊朗', 'IRAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('277', 'IN', '印度', 'INDIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('279', 'GB', '英国', 'UNITED KINGDOM');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('281', 'IL', '以色列', 'ISRAEL');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('282', 'BR', '巴西', 'BRAZIL');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('285', 'JO', '约旦', 'JORDAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('286', 'VN', '越南', 'VIETNAM');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('288', 'TD', '乍得', 'CHAD');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('289', 'ZM', '赞比亚', 'ZAMBIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('297', 'GI', '直布罗陀', 'GIBRALTAR');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('298', 'CL', '智利', 'CHILE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('299', 'CF', '中非', 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('303', 'AR', '阿根廷', 'ARGENTINA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('308', 'BJ', '贝宁', 'BENIN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('309', 'BE', '比利时', 'BELGIUM');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('310', 'IS', '冰岛', 'ICELAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('311', 'BW', '博茨瓦纳', 'BOTSWANA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('312', 'PR', '波多黎各', 'PUERTO RICO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('313', 'BA', '波黑', 'BOSNIA AND HERZEGOVINA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('314', 'PL', '波兰', 'POLAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('315', 'IE', '爱尔兰', 'IRELAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('316', 'BO', '玻利维亚', 'BOLIVIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('317', 'BZ', '伯利兹', 'BELIZE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('318', 'BT', '不丹', 'BHUTAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('319', 'BI', '布隆迪', 'BURUNDI');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('324', 'EG', '埃及', 'EGYPT');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('326', 'KP', '朝鲜', 'DEMOCRATIC PEOPLES REPUBLIC OF KOREA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('334', 'DK', '丹麦', 'DENMARK');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('338', 'DE', '德国', 'GERMANY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('344', 'TG', '多哥', 'TOGO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('345', 'EE', '爱沙尼亚', 'ESTONIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('347', 'EC', '厄瓜多尔', 'ECUADOR');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('348', 'RU', '俄罗斯', 'RUSSIAN FEDERATION');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('350', 'FR', '法国', 'FRANCE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('351', 'FO', '法罗群岛', 'FAROE ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('352', 'FJ', '斐济', 'FIJI');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('353', 'PH', '菲律宾', 'PHILIPPINES');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('354', 'AE', '阿联酋', 'UNITED ARAB EMIRATES');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('356', 'FI', '芬兰', 'FINLAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('360', 'GM', '冈比亚', 'GAMBIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('363', 'AL', '阿尔巴尼亚', 'ALBANIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('364', 'CR', '哥斯达黎加', 'COSTA RICA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('365', 'KZ', '哈萨克斯坦', 'KAZAKHSTAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('366', 'AN', '荷属安的列斯群岛', 'NETHERLANDS ANTILLES');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('367', 'KG', '吉尔吉斯斯坦', 'KYRGYZSTAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('368', 'LI', '列支敦士登', 'LIECHTENSTEIN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('369', 'MG', '马达加斯加', 'MADAGASCAR');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('370', 'DZ', '阿尔及利亚', 'ALGERIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('371', 'MR', '毛里塔尼亚', 'MAURITANIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('372', 'MH', '马绍尔群岛', 'MARSHALL ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('373', 'AS', '美属萨摩亚', 'AMERICAN SAMOA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('374', 'VI', '美属维尔京群岛', 'UNITED STATES VIRGIN ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('375', 'FM', '密克罗尼西亚', 'MICRONESIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('376', 'PG', '巴布亚新几内亚', 'PAPUA NEW GUINEA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('377', 'SA', '沙特阿拉伯', 'SAUDI ARABIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('378', 'PM', '圣皮埃尔和密克隆', 'SAINT PIERRE AND MIQUELON');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('379', 'SI', '斯洛文尼亚', 'SLOVENIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('380', 'TT', '特立尼达和多巴哥', 'TRINIDAD AND TOBAGO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('382', 'UZ', '乌兹别克斯坦', 'UZBEKISTAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('383', 'NC', '新喀里多尼亚', 'NEW CALEDONIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('384', 'ID', '印度尼西亚', 'INDONESIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('385', 'VG', '英属维尔京', 'THE BRITISH VRIGIN ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('387', 'PF', '波利尼西亚', 'POLYNESIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('388', 'BF', '布基纳法索', 'BURKINA FASO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('389', 'ET', '埃塞俄比亚', 'ETHIOPIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('390', 'PF', '法属波利尼西亚', 'FRENCH POLYNESIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('391', 'GF', '法属圭亚那', 'FRENCH GUIANA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('395', 'KI', '基里巴斯', 'KIRIBATI');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('397', 'SO', '索马里', 'SOMALIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('398', 'ER', '厄立特里亚', 'ERITREA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('400', 'GD', '格林纳达', 'GRENADA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('401', 'AI', '安圭拉', 'ANGUILLA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('404', 'GW', '几内亚比绍', 'GUINEA-BISSAU');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('408', 'LC', '圣卢西亚', 'SAINT LUCIA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('410', 'JE', '泽西岛', 'JERSEY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('411', 'GG', '格恩西岛', 'GUERNSEY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('413', 'PT', '马德拉群岛', 'MADEIRA ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('414', 'PT', '亚速尔群岛', 'AZORES');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('415', 'ES', '巴利阿里群岛', 'BALEARIC ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('419', 'MF', '圣马丁', 'SAINT MARTIN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('533', 'LS', '莱索托', 'LESOTHO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('564', 'WF', '瓦利斯和富图纳群岛', 'WALLIS AND FUTUNA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('715', 'MP', '北马里亚纳群岛', 'NORTHERN MARIANA ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('823', 'ME', '黑山', 'MONTENEGRO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2714', 'IC', '加那利群岛', 'CANARY ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2747', 'VA', '梵蒂冈', 'VATICAN CITY STATE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2750', 'FK', '福克兰群岛', 'ISLAS MALVINAS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2751', 'TJ', '塔吉克斯坦', 'TAJIKISTAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2753', 'GQ', '赤道几内亚', 'EQUATORIAL GUINEA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2754', 'VC', '圣文森特和格林纳丁斯', 'SAINT VINCENT AND THE GRENADINES');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2756', 'YT', '法属马约特岛', 'TERRITORIAL COLLECTIVITY OF MAYOTTE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2758', 'TC', '特克斯和凯科斯群岛', 'TURKS AND CAICOS ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2759', 'SB', '所罗门群岛', 'SOLOMON ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2760', 'NULL', '尼维斯', 'THE FEDERATION OF NEVIS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2763', 'EH', '西撒哈拉', 'WESTERN SAHARA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2764', 'TM', '土库曼斯坦', 'TURKMENISTAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2765', 'CV', '佛得角', 'CAPE VERDE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2766', 'NR', '瑙鲁共和国', 'NAURU');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2767', 'NULL', '塞班岛', 'SAIPAN LSLAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2771', 'NF', '诺福克岛', 'NORFOLK ISLAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2772', 'KS', '科索沃', 'KOSOVO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2776', 'CW', '库拉索', 'CURACAO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2777', 'GG', '根西岛', 'GUERNSEY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2778', 'KN', '圣基茨和尼维斯联邦', 'SAINT KITTS AND NEVIS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2779', 'MS', '蒙特塞拉特', 'MONTSERRAT');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2780', 'CD', '刚果(金)', 'THE DEMOCRATIC REPUBLIC OF THE CONGO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2781', 'CG', '刚果(布)', 'CONGO');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2782', 'Z2', '阿森松岛', 'ASCENSION ISLAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2783', 'TL', '东帝汶', 'TIMOR-LESTE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2785', 'NU', '纽埃', 'NIUE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2786', 'PN', '皮特凯恩群岛', 'PITCAIRN ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2787', 'CX', '圣诞岛', 'CHRISTMAS ISLAND');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2788', 'ST', '圣多美和普林西比', 'SAO TOME AND PRINCIPE');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2789', 'SH', '圣赫勒拿', 'SAINT HELENA');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2790', 'TV', '图瓦卢', 'TUVALU');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2791', 'TK', '托克劳', 'TOKELAU');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2793', 'IM', '马恩岛', 'ISLE OF MAN');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2795', 'NULL', '马里亚纳群岛', 'MARIANA LSLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2816', 'DO', '多米尼加共和国', 'DOMINICAN REPUBLIC');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2826', 'GS', '南乔治亚岛和南桑威奇群岛', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2828', 'IO', '英属印度洋领地', 'BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO t_country(`id`, `bcode`, `name`, `english_name`) values ('2834', 'UM', '美国本土外小岛屿', 'UNITED STATES MINOR OUTLYING ISLANDS');

DROP TABLE IF EXISTS `t_city`;
CREATE TABLE `t_city`  (
  `id` varchar(16) NOT NULL COMMENT 'id',
  `name` varchar(256) NOT NULL COMMENT '名字',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_name`(`name`)
) ENGINE = InnoDB COMMENT = '城市表';

INSERT INTO t_city(`id`, `name`) values ('06', '杭州');